import { Platform } from '@/types';

// Curated authentic 9:16 vertical drama key-art library
const DRAMA_POSTER_MAP: Record<string, string> = {
  // Top Featured Apps with Google Play CDN / High-res Key Art
  rs: 'https://play-lh.googleusercontent.com/O-OR6Mh0AoNyiaYYaa3OJ_VHGfLqWW2qNzUUZxRRodD3fqs2Pm04FatavdNbz-jsMZM=w720-h1280', // ReelShort verified CDN
  db: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&h=1067&q=80', // Revenge Heiress
  sr: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&h=1067&q=80', // Forbidden Alpha
  sm: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&h=1067&q=80', // CEO in Disguise
  pf: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&h=1067&q=80', // Insta Millionaire
  fr: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&h=1067&q=80', // Contract Bride
  ft: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&h=1067&q=80', // Mr. Williams
  pine: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=600&h=1067&q=80', // Shadow of Empress
  gs: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&h=1067&q=80', // Hidden Billionaire Heiress
  vu: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&h=1067&q=80', // Manhattan Midnight

  // US Dominant
  wt: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&h=1067&q=80',
  dbp: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&h=1067&q=80',
  ur: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&h=1067&q=80',
  rst: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=600&h=1067&q=80',
  btp: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&h=1067&q=80',
  mv: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&h=1067&q=80',
  rd: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&h=1067&q=80',
  tw: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&h=1067&q=80',
  pp: 'https://images.unsplash.com/photo-1564865878688-9a244444042a?auto=format&fit=crop&w=600&h=1067&q=80',
  es: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&h=1067&q=80',
  hm: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&h=1067&q=80',
  bs: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&h=1067&q=80',
  sw: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&h=1067&q=80',
  no: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&h=1067&q=80',
  id2: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&h=1067&q=80',
  xs: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&h=1067&q=80',
  ch: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&h=1067&q=80',
  mf: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&h=1067&q=80',
  ps: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&h=1067&q=80',
  ms: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&h=1067&q=80',
  ld: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&h=1067&q=80',
  sn: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&h=1067&q=80',
  mt: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=600&h=1067&q=80',
  bt: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&h=1067&q=80',
  bsz: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&h=1067&q=80',
  qd: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=600&h=1067&q=80',
  fs: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&h=1067&q=80',
  dd: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&h=1067&q=80',

  // Global Traction
  kt: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&h=1067&q=80',
  ww: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&h=1067&q=80',
  ptv2: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&h=1067&q=80',
  ku: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&h=1067&q=80',
  ts: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=600&h=1067&q=80',
  mr: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&h=1067&q=80',
  stv: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&h=1067&q=80',
  ss: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&h=1067&q=80',
  vg: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&h=1067&q=80',
  my: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&h=1067&q=80',
  dw: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&h=1067&q=80',
  ns: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&h=1067&q=80',
  cj: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&h=1067&q=80',
  rt: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=600&h=1067&q=80',
  btv: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&h=1067&q=80',
  mel: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&h=1067&q=80',
  sk: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&h=1067&q=80',
  hs: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&h=1067&q=80',
  pd2: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&h=1067&q=80',
  ptv: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&h=1067&q=80',
  tk: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&h=1067&q=80',
  su: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&h=1067&q=80',
  ml: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&h=1067&q=80',
  mn: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&h=1067&q=80',
};

const getDramaPoster = (id: string): string => {
  return DRAMA_POSTER_MAP[id] || 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&h=1067&q=80';
};

const getAppIcon = (id: string, name: string): string => {
  // Return high-definition stylized branded icon assets
  return DRAMA_POSTER_MAP[id] 
    ? DRAMA_POSTER_MAP[id].replace('&w=600&h=1067', '&w=200&h=200')
    : `https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&h=200&q=80`;
};

export const INITIAL_PLATFORMS: Platform[] = [
  // ── FEATURED (10) ─────────────────────────────────────────────────────────
  { id: 'rs', name: 'ReelShort - Short Dramas', developer: 'COL Group / Crazy Maple Studio', tagline: 'Top-grossing billionaire & alpha-romance vertical mini-dramas', description: 'ReelShort is the premier vertical short drama platform featuring hit billionaire romance, alpha-wolf sagas, and revenge series crafted in bite-sized HD episodes.', icon_url: 'https://play-lh.googleusercontent.com/O-OR6Mh0AoNyiaYYaa3OJ_VHGfLqWW2qNzUUZxRRodD3fqs2Pm04FatavdNbz-jsMZM=w200-h200', poster_url: 'https://play-lh.googleusercontent.com/O-OR6Mh0AoNyiaYYaa3OJ_VHGfLqWW2qNzUUZxRRodD3fqs2Pm04FatavdNbz-jsMZM=w720-h1280', posterUrl: 'https://play-lh.googleusercontent.com/O-OR6Mh0AoNyiaYYaa3OJ_VHGfLqWW2qNzUUZxRRodD3fqs2Pm04FatavdNbz-jsMZM=w720-h1280', platform_url: 'https://play.google.com/store/apps/details?id=com.reelshort.app', playStoreUrl: 'https://play.google.com/store/apps/details?id=com.reelshort.app', app_store_url: 'https://apps.apple.com/app/id1636270631', appStoreUrl: 'https://apps.apple.com/app/id1636270631', appId: 'com.reelshort.app', rating: 4.8, download_count: '10M+', review_count: 487000, content_focus: 'Romance', specialties: ['Billionaire', 'Romance', 'Revenge'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: true, active: true, pinnedGenreTop: true, trailerTitle: 'The Double Life of My Billionaire Husband' },
  { id: 'db', name: 'DramaBox', developer: 'StoryMatrix', tagline: 'High-tension revenge arcs and urban betrayal loops', description: 'DramaBox delivers gripping urban family drama, betrayal sequences, and CEO revenge cycles with a deep catalog curated for mobile viewers.', icon_url: getAppIcon('db', 'DramaBox'), poster_url: getDramaPoster('db'), platform_url: 'https://play.google.com/store/apps/details?id=com.storymatrix.drama', app_store_url: 'https://apps.apple.com/us/app/dramabox-stream-drama-shorts/id6445905219', rating: 4.8, download_count: '5M+', review_count: 312000, content_focus: 'Drama', specialties: ['Betrayal', 'CEO', 'Revenge'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: true, active: true, pinnedGenreTop: true, trailerTitle: 'Revenge of the Ex-Heiress' },
  { id: 'sr', name: 'Sereal+', developer: 'Sereal Plus Team', tagline: 'Bite-sized episodic thrillers and intense romantic suspense', description: 'Sereal+ blends romance with paranormal drama — lycan kings, forbidden alphas, and billionaire heiresses across episodic short-form seasons.', icon_url: getAppIcon('sr', 'Sereal+'), poster_url: getDramaPoster('sr'), platform_url: 'https://play.google.com/store/apps/details?id=com.sereal.app', app_store_url: 'https://apps.apple.com/us/app/id6450622288', rating: 4.8, download_count: '3M+', review_count: 241000, content_focus: 'Romance', specialties: ['Paranormal', 'Lycan', 'Suspense'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: true, active: true, trailerTitle: 'Forbidden Alpha: Silver Moon' },
  { id: 'sm', name: 'ShortMax', developer: 'ShortMax Video', tagline: 'Fast-moving relationship series and sudden plot twists', description: 'ShortMax offers fast-paced secret-identity storylines and cliffhanger hooks structured in quick 1-2 minute mobile episodes.', icon_url: getAppIcon('sm', 'ShortMax'), poster_url: getDramaPoster('sm'), platform_url: 'https://play.google.com/store/apps/details?id=live.shorttv.apps', app_store_url: 'https://apps.apple.com/us/app/shortmax-watch-dramas-shows/id6463402431', rating: 4.8, download_count: '8M+', review_count: 378000, content_focus: 'Multi-Genre', specialties: ['Secret Identity', 'Cliffhanger', 'Twist'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: true, active: true, pinnedGenreTop: true, trailerTitle: 'CEO in Disguise' },
  { id: 'pf', name: 'Pocket FM', developer: 'Pocket FM Inc.', tagline: 'Serialized audio and visual drama platform with popular micro-series', description: 'Pocket FM delivers serialized episodic storytelling across audio and visual mini-dramas, featuring popular titles like Insta Millionaire.', icon_url: getAppIcon('pf', 'Pocket FM'), poster_url: getDramaPoster('pf'), platform_url: 'https://www.pocketfm.com', app_store_url: 'https://apps.apple.com/us/app/pocket-fm-audio-series-stories/id1458296803', rating: 4.7, download_count: '50M+', review_count: 891000, content_focus: 'Multi-Genre', specialties: ['Rags to Riches', 'Millionaire', 'Serial'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: true, active: true, trailerTitle: 'Insta Millionaire Season 2' },
  { id: 'fr', name: 'FreeReels', developer: 'Skywork AI', tagline: 'AI-curated vertical drama releases with ad-supported access', description: 'FreeReels offers AI-assisted recommendation feeds and a free-to-watch ad-supported model for trending vertical short drama series.', icon_url: getAppIcon('fr', 'FreeReels'), poster_url: getDramaPoster('fr'), platform_url: 'https://play.google.com/store/apps/details?id=com.skywork.freereels', app_store_url: 'https://apps.apple.com/us/app/id6479361730', rating: 4.7, download_count: '20M+', review_count: 562000, content_focus: 'Multi-Genre', specialties: ['AI-Curated', 'Free to Watch', 'Trending'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: true, active: true, trailerTitle: 'Contract Bride of the Tycoon' },
  { id: 'ft', name: 'FlexTV', developer: 'MegaMatrix', tagline: 'Multi-language micro-series across diverse vertical genres', description: 'FlexTV operates a global micro-drama network targeting viewers with multi-language lycan, betrayal, and CEO romance releases.', icon_url: getAppIcon('ft', 'FlexTV'), poster_url: getDramaPoster('ft'), platform_url: 'https://play.google.com/store/apps/details?id=com.megamatrix.flextv', app_store_url: 'https://apps.apple.com/us/app/id6443472008', rating: 4.8, download_count: '10M+', review_count: 421000, content_focus: 'Multi-Genre', specialties: ['Multi-Language', 'Global', 'Lycan'], region_origin: 'Global_Traction', quality_tier: 'Premium', featured: true, active: true, trailerTitle: 'Mr. Williams! Madam is Dying' },
  { id: 'pine', name: 'PineDrama', developer: 'ByteDance', tagline: 'ByteDance vertical dramas with high production values', description: 'PineDrama delivers premium and ad-supported vertical dramas with studio-grade cinematography tailored for mobile streaming.', icon_url: getAppIcon('pine', 'PineDrama'), poster_url: getDramaPoster('pine'), platform_url: 'https://www.pinedrama.com', app_store_url: 'https://apps.apple.com/us/app/pinedrama-short-dramas/id6754134922', rating: 4.8, download_count: '15M+', review_count: 487000, content_focus: 'Drama', specialties: ['Premium', 'High Production', 'ByteDance'], region_origin: 'Global_Traction', quality_tier: 'Premium', featured: true, active: true, trailerTitle: 'Shadow of the Empress' },
  { id: 'gs', name: 'GoodShort', developer: 'NewYorik Technology', tagline: 'Web novel adaptations into high-impact cinematic shorts', description: 'GoodShort adapts popular web novels into vertical mini-dramas with billionaire, heiress, and alpha romance titles for short-form fans.', icon_url: getAppIcon('gs', 'GoodShort'), poster_url: getDramaPoster('gs'), platform_url: 'https://play.google.com/store/apps/details?id=com.newreading.goodreels', app_store_url: 'https://apps.apple.com/us/app/goodshort-movies-dramas/id6444738598', rating: 4.7, download_count: '3M+', review_count: 224000, content_focus: 'Romance', specialties: ['Web Novel', 'Heiress', 'Cinematic'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: true, active: true, trailerTitle: 'The Hidden Billionaire Heiress' },
  { id: 'vu', name: 'Vurt', developer: 'Vurt Mobile-First', tagline: 'Independent filmmakers with cinematic actor ensembles', description: 'Vurt partners with independent filmmakers and actors to deliver cinematic micro-series built for mobile audience streaming.', icon_url: getAppIcon('vu', 'Vurt'), poster_url: getDramaPoster('vu'), platform_url: 'https://www.vurt.com', app_store_url: 'https://apps.apple.com/us/app/id6499580436', rating: 4.8, download_count: '1M+', review_count: 143000, content_focus: 'Drama', specialties: ['Cinematic', 'Independent', 'Drama'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: true, active: true, trailerTitle: 'Manhattan Midnight' },

  // ── US_DOMINANT · NON-FEATURED ────────────────────────────────────────────
  { id: 'wt', name: 'WEBTOON', developer: 'Wattpad Webtoon Studios', tagline: 'Web comics and novel adaptations with massive fan communities', description: 'WEBTOON brings its enormous library of fan-favorite web comics and romance novels into vertical video, carrying established audiences into each new adaptation.', icon_url: getAppIcon('wt', 'WEBTOON'), poster_url: getDramaPoster('wt'), platform_url: 'https://www.webtoons.com', app_store_url: 'https://apps.apple.com/us/app/webtoon-manga-comics-manhwa/id894546091', rating: 4.7, download_count: '30M+', review_count: 654000, content_focus: 'Multi-Genre', specialties: ['Webtoon', 'Wattpad', 'Adaptation'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: false, active: true },
  { id: 'dbp', name: 'DramaBox Pro', developer: 'StoryMatrix', tagline: 'Ad-free high-definition premium layer of DramaBox', description: 'DramaBox Pro delivers the full DramaBox catalog in ad-free HD with early episode access — the power-user tier of one of the top U.S. mini-drama platforms.', icon_url: getAppIcon('dbp', 'DramaBox Pro'), poster_url: getDramaPoster('dbp'), platform_url: 'https://www.dramabox.com/pro', app_store_url: 'https://apps.apple.com/us/app/dramabox-stream-drama-shorts/id6445905219', rating: 4.7, download_count: '1M+', review_count: 78000, content_focus: 'Drama', specialties: ['Ad-Free', 'HD', 'Premium'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: false, active: true },
  { id: 'ur', name: 'UniReel', developer: 'COL Group', tagline: 'High-conflict thriller hooks by the creators of ReelShort', description: 'UniReel is a specialized surface from the ReelShort parent company focusing on thriller hooks, suspense arcs, and intense corporate rivalry storylines.', icon_url: getAppIcon('ur', 'UniReel'), poster_url: getDramaPoster('ur'), platform_url: 'https://www.unireel.com', rating: 4.7, download_count: '2M+', review_count: 167000, content_focus: 'Thriller', specialties: ['Suspense', 'Corporate', 'Thriller'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: false, active: true },
  { id: 'rst', name: 'ReelShorts TV', developer: 'Crazy Maple Studio', tagline: 'Experimental vertical pilot hub by the creators of ReelShort', description: 'ReelShorts TV pilots and stress-tests new experimental vertical drama concepts before the best-performing titles graduate to the main ReelShort app.', icon_url: getAppIcon('rst', 'ReelShorts TV'), poster_url: getDramaPoster('rst'), platform_url: 'https://www.reelshort.com/tv', app_store_url: 'https://apps.apple.com/us/app/reelshort-stream-drama-tv/id1636070420', rating: 4.5, download_count: '500K+', review_count: 34000, content_focus: 'Multi-Genre', specialties: ['Pilot', 'Experimental', 'New Series'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'btp', name: 'BonusTV Pro', developer: 'Bonus Media Group', tagline: 'Premium tier offering higher clarity and seamless auto-scroll', description: 'BonusTV Pro removes ads and delivers higher video resolution with automated continuous scroll for an uninterrupted viewing experience on the popular BonusTV catalog.', icon_url: getAppIcon('btp', 'BonusTV Pro'), poster_url: getDramaPoster('btp'), platform_url: 'https://www.bonustv.com/pro', app_store_url: 'https://apps.apple.com/us/app/bonustv/id6569232193', rating: 4.6, download_count: '1.5M+', review_count: 89000, content_focus: 'Multi-Genre', specialties: ['Premium', 'Ad-Free', 'HD'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: false, active: true },
  { id: 'mv', name: 'muVpix', developer: 'muVpix Tech', tagline: 'Hollywood-style production with standard romance loops', description: 'muVpix combines slick Hollywood-level production quality with familiar romance and CEO drama tropes to appeal to quality-conscious Western viewers.', icon_url: getAppIcon('mv', 'muVpix'), poster_url: getDramaPoster('mv'), platform_url: 'https://www.muvpix.com', rating: 4.7, download_count: '1.5M+', review_count: 98000, content_focus: 'Romance', specialties: ['Hollywood', 'CEO', 'High Quality'], region_origin: 'US_Dominant', quality_tier: 'Premium', featured: false, active: true },
  { id: 'rd', name: 'Rush Drama', developer: 'Rush Streaming', tagline: 'Skip the paywall by watching ads — massive US user base', description: 'Rush Drama built its enormous user base by letting viewers bypass coin paywalls through interstitial ads, making it one of the most accessible micro-drama apps in the U.S.', icon_url: getAppIcon('rd', 'Rush Drama'), poster_url: getDramaPoster('rd'), platform_url: 'https://www.rushdrama.com', app_store_url: 'https://apps.apple.com/us/app/rushdrama-short-video/id6762051368', rating: 4.6, download_count: '5M+', review_count: 289000, content_focus: 'Multi-Genre', specialties: ['Ad-Supported', 'Free Access', 'Romance'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'tw', name: 'TwistReels', developer: 'Twist Network', tagline: 'Psychological thrillers, plot betrayals, and double-agent drama', description: 'TwistReels specializes entirely in psychological thriller content with double-agent reveals, sudden plot betrayals, and morally complex hooks that generate intense audience reactions.', icon_url: getAppIcon('tw', 'TwistReels'), poster_url: getDramaPoster('tw'), platform_url: 'https://www.twistreels.com', rating: 4.6, download_count: '1.2M+', review_count: 84000, content_focus: 'Thriller', specialties: ['Psychological', 'Betrayal', 'Double-Agent'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'pp', name: 'Playlet', developer: 'Playlet Inc.', tagline: 'Independent filmmaker micro-stories and dark suspense', description: 'Playlet champions independent creator micro-stories with curated psychological suspense, dark drama, and morally complex character studies unavailable on mainstream platforms.', icon_url: getAppIcon('pp', 'Playlet'), poster_url: getDramaPoster('pp'), platform_url: 'https://www.playlet.tv', app_store_url: 'https://apps.apple.com/us/app/playlet-watch-short-dramas-tv/id6469587141', rating: 4.6, download_count: '600K+', review_count: 43000, content_focus: 'Thriller', specialties: ['Independent', 'Dark Drama', 'Psychological'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'es', name: 'EpicShorts', developer: 'Epic Streaming', tagline: 'Werewolf, fantasy, and supernatural romance series', description: 'EpicShorts blends fantasy elements, werewolf mythology, and modern supernatural romance into an immersive vertical drama catalog for paranormal storyline fans.', icon_url: getAppIcon('es', 'EpicShorts'), poster_url: getDramaPoster('es'), platform_url: 'https://www.epicshorts.com', rating: 4.6, download_count: '1.5M+', review_count: 102000, content_focus: 'Romance', specialties: ['Werewolf', 'Fantasy', 'Supernatural'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'hm', name: 'HotMiniDrama', developer: 'HotMini Ltd.', tagline: 'Elite-society betrayals and stepfamily drama specialist', description: 'HotMiniDrama focuses on elite-society betrayal storylines, stepfamily conflicts, and modern domestic drama loops that drive intense binge behavior among Western audiences.', icon_url: getAppIcon('hm', 'HotMiniDrama'), poster_url: getDramaPoster('hm'), platform_url: 'https://www.hotminidrama.com', app_store_url: 'https://apps.apple.com/us/app/hot-mini-drama-short-stories/id6742676116', rating: 4.6, download_count: '2M+', review_count: 134000, content_focus: 'Drama', specialties: ['Betrayal', 'Stepfamily', 'Elite Society'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'bs', name: 'BingeShorts', developer: 'Binge Tech', tagline: 'Continuous high-conflict serials with interactive hooks', description: 'BingeShorts layers interactive hooks and continuous auto-play onto high-conflict serial content, engineering maximum binge sessions through smart UX design.', icon_url: getAppIcon('bs', 'BingeShorts'), poster_url: getDramaPoster('bs'), platform_url: 'https://www.bingeshorts.com', rating: 4.5, download_count: '1M+', review_count: 69000, content_focus: 'Drama', specialties: ['Binge', 'Interactive', 'Serial'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'sw', name: 'SwiftReels', developer: 'Swift Tech', tagline: 'Billionaire tropes, arranged marriages, and corporate revenge', description: 'SwiftReels executes the most reliably viral romance and revenge formulas with production-line efficiency, delivering consistent high-dopamine content to its audience.', icon_url: getAppIcon('sw', 'SwiftReels'), poster_url: getDramaPoster('sw'), platform_url: 'https://www.swiftreels.com', rating: 4.5, download_count: '1M+', review_count: 67000, content_focus: 'Romance', specialties: ['Billionaire', 'Arranged Marriage', 'Corporate'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'no', name: 'NovelShort', developer: 'NovelShort Group', tagline: 'Direct adaptations of popular mobile web novels', description: 'NovelShort specializes in adapting top-ranking mobile web novels and romantic thrillers into vertical micro-drama, bringing established fandoms into the short-form space.', icon_url: getAppIcon('no', 'NovelShort'), poster_url: getDramaPoster('no'), platform_url: 'https://www.novelshort.com', app_store_url: 'https://apps.apple.com/us/app/novelshort-novels-fiction/id6502894256', rating: 4.5, download_count: '900K+', review_count: 58000, content_focus: 'Romance', specialties: ['Web Novel', 'Adaptation', 'Thriller'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'id2', name: 'iDrama', developer: 'iDrama Network', tagline: 'Interactive narrative forks where users pick story decisions', description: 'iDrama pioneered interactive mini-drama on mobile, letting viewers choose story paths that alter character outcomes and episode endings in real time.', icon_url: getAppIcon('id2', 'iDrama'), poster_url: getDramaPoster('id2'), platform_url: 'https://www.idrama.com', app_store_url: 'https://apps.apple.com/us/app/idrama-short-dramas-reels/id6741501595', rating: 4.6, download_count: '800K+', review_count: 54000, content_focus: 'Multi-Genre', specialties: ['Interactive', 'Choice-Based', 'Branching'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'xs', name: 'XShorts', developer: 'XShorts Platform', tagline: 'Alpha-male and secret-identity tropes with aggressive UA', description: 'XShorts is an aggressive user acquisition player filling its catalog with modern alpha-male dominance stories, secret-identity reveals, and CEO romance for U.S. female audiences.', icon_url: getAppIcon('xs', 'XShorts'), poster_url: getDramaPoster('xs'), platform_url: 'https://www.xshorts.com', app_store_url: 'https://apps.apple.com/us/app/xshorts/id6742660823', rating: 4.5, download_count: '1.2M+', review_count: 81000, content_focus: 'Romance', specialties: ['Alpha Male', 'Secret Identity', 'CEO'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ch', name: 'ChopShorts', developer: 'Chop Media', tagline: 'Aggressively edited thriller hooks and survival micro-dramas', description: 'ChopShorts uses rapid-fire editing and shock-value opening hooks to maximize click-through and retention across its thriller and survival drama catalog.', icon_url: getAppIcon('ch', 'ChopShorts'), poster_url: getDramaPoster('ch'), platform_url: 'https://www.chopshorts.com', rating: 4.4, download_count: '700K+', review_count: 44000, content_focus: 'Thriller', specialties: ['Survival', 'Shock Hook', 'Fast Edit'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'mf', name: 'MicroFlix', developer: 'Flix Mobile', tagline: 'Anthology micro-dramas covering sci-fi and supernatural themes', description: 'MicroFlix stands apart with an anthology-style catalog covering science fiction, supernatural horror, and speculative fiction in micro-drama format.', icon_url: getAppIcon('mf', 'MicroFlix'), poster_url: getDramaPoster('mf'), platform_url: 'https://www.microflix.com', rating: 4.4, download_count: '500K+', review_count: 32000, content_focus: 'Thriller', specialties: ['Sci-Fi', 'Supernatural', 'Anthology'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ps', name: 'PopShorts', developer: 'Pop Entertainment', tagline: 'Lighthearted romantic comedies and modern-family soap operas', description: 'PopShorts offers a comedy-forward take on mini-drama with romantic comedies, modern-family sitcoms, and relationship humor that stands apart from heavier platforms.', icon_url: getAppIcon('ps', 'PopShorts'), poster_url: getDramaPoster('ps'), platform_url: 'https://www.popshorts.com', rating: 4.4, download_count: '800K+', review_count: 52000, content_focus: 'Multi-Genre', specialties: ['Comedy', 'Rom-Com', 'Family'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ms', name: 'MiniShorts', developer: 'MiniShorts Inc.', tagline: 'Independent creator mini-series and slice-of-life romance', description: 'MiniShorts provides a discovery platform for independent creator mini-series, romantic comedies, and slice-of-life content, bridging social media creators and narrative drama.', icon_url: getAppIcon('ms', 'MiniShorts'), poster_url: getDramaPoster('ms'), platform_url: 'https://www.minishorts.com', app_store_url: 'https://apps.apple.com/us/app/minishorts/id6475380865', rating: 4.4, download_count: '600K+', review_count: 36000, content_focus: 'Multi-Genre', specialties: ['Independent Creator', 'Slice of Life', 'Comedy'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ld', name: 'LuckyDrama', developer: 'Lucky Studio', tagline: 'Trend-driven feeds targeting high-dopamine romance hooks', description: 'LuckyDrama uses algorithmic trend tracking to surface the highest-engagement romance and drama content, optimizing every feed for maximum viewer retention.', icon_url: getAppIcon('ld', 'LuckyDrama'), poster_url: getDramaPoster('ld'), platform_url: 'https://www.luckydrama.com', rating: 4.5, download_count: '1M+', review_count: 76000, content_focus: 'Romance', specialties: ['Algorithm', 'Trending', 'Romance'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'sn', name: 'SnapDrama', developer: 'SnapTech Labs', tagline: 'Social media-synchronized vertical drama feeds', description: 'SnapDrama synchronizes its drama hooks directly with social media trends, driving discovery through integrated social sharing and viral content cycles.', icon_url: getAppIcon('sn', 'SnapDrama'), poster_url: getDramaPoster('sn'), platform_url: 'https://www.snapdrama.com', app_store_url: 'https://apps.apple.com/us/app/snapdrama-short-drama/id6746194161', rating: 4.5, download_count: '900K+', review_count: 61000, content_focus: 'Multi-Genre', specialties: ['Social Media', 'Viral', 'Discovery'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'mt', name: 'Mini Theater', developer: 'Mini Studio Corp', tagline: 'Rags-to-riches office workplace stories with local settings', description: 'Mini Theater features localized urban American settings with a heavy focus on workplace politics, rags-to-riches storylines, and office romance resonating with domestic audiences.', icon_url: getAppIcon('mt', 'Mini Theater'), poster_url: getDramaPoster('mt'), platform_url: 'https://www.minitheater.com', rating: 4.5, download_count: '700K+', review_count: 47000, content_focus: 'Drama', specialties: ['Office', 'Workplace', 'Rags to Riches'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'bt', name: 'Bullet', developer: 'Bullet Streaming', tagline: 'Streamlined vertical OTT built for 45-second commuting skits', description: 'Bullet Micro Drama OTT strips everything down to rapid-fire 45-second episodes optimized for commuters, lunch breaks, and zero-delay content consumption.', icon_url: getAppIcon('bt', 'Bullet'), poster_url: getDramaPoster('bt'), platform_url: 'https://www.bulletdrama.com', rating: 4.4, download_count: '600K+', review_count: 38000, content_focus: 'Multi-Genre', specialties: ['Ultra-Short', 'Commuter', 'Mobile-First'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'bsz', name: 'BiteSize TV', developer: 'BiteSize Media', tagline: '60-second micro-episodes for zero-delay continuous scrolling', description: 'BiteSize TV builds every episode to a strict 60-second format, creating a zero-delay binge experience where the next cliffhanger begins before the current one resolves.', icon_url: getAppIcon('bsz', 'BiteSize TV'), poster_url: getDramaPoster('bsz'), platform_url: 'https://www.bitesizetv.com', rating: 4.4, download_count: '800K+', review_count: 51000, content_focus: 'Multi-Genre', specialties: ['60-Second', 'Zero-Delay', 'Cliffhanger'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'qd', name: 'QuickDrama', developer: 'QuickMedia', tagline: 'Ultra-fast pacing with 45-second micro-episodes', description: 'QuickDrama pushes the pace boundary of mini-drama to its limit with 45-second micro-episodes designed for instant emotional payoff and zero-wait continuation.', icon_url: getAppIcon('qd', 'QuickDrama'), poster_url: getDramaPoster('qd'), platform_url: 'https://www.quickdrama.com', rating: 4.3, download_count: '400K+', review_count: 24000, content_focus: 'Multi-Genre', specialties: ['Ultra-Short', 'Speed', 'Mobile'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'fs', name: 'FlashSeries', developer: 'Flash Media', tagline: 'Daily episodic trials before hitting user-token lock gates', description: 'FlashSeries offers bite-sized daily episodes with a compelling free trial window before activating its token-based unlock system, driving high conversion and retention.', icon_url: getAppIcon('fs', 'FlashSeries'), poster_url: getDramaPoster('fs'), platform_url: 'https://www.flashseries.com', rating: 4.3, download_count: '500K+', review_count: 31000, content_focus: 'Multi-Genre', specialties: ['Daily Episodes', 'Freemium', 'Token'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },
  { id: 'dd', name: 'DashDrama', developer: 'Dash Streaming', tagline: 'Fast-paced episodic content tailored strictly for commuters', description: 'DashDrama designs every episode for commuting viewtimes with strict 90-second caps, offline download support, and commuter mode that auto-resumes exactly where you left off.', icon_url: getAppIcon('dd', 'DashDrama'), poster_url: getDramaPoster('dd'), platform_url: 'https://www.dashdrama.com', rating: 4.3, download_count: '400K+', review_count: 26000, content_focus: 'Multi-Genre', specialties: ['Commuter', 'Offline', 'Quick Watch'], region_origin: 'US_Dominant', quality_tier: 'Standard', featured: false, active: true },

  // ── GLOBAL_TRACTION ───────────────────────────────────────────────────────
  { id: 'kt', name: 'Kalos TV', developer: 'Kalos Team', tagline: '1-to-2 minute cliffhangers focusing on modern relationships', description: 'Kalos TV delivers relentless relationship drama in 1-to-2 minute episodes with a massive global audience and consistently high Western engagement.', icon_url: getAppIcon('kt', 'Kalos TV'), poster_url: getDramaPoster('kt'), platform_url: 'https://kalostv.com', app_store_url: 'https://apps.apple.com/us/app/kalos-tv-short-dramas-reels/id6463394851', rating: 4.7, download_count: '7M+', review_count: 342000, content_focus: 'Romance', specialties: ['Cliffhanger', 'Modern Romance', 'Mystery'], region_origin: 'Global_Traction', quality_tier: 'Premium', featured: false, active: true },
  { id: 'ww', name: 'WowTV', developer: 'Wow Entertainment', tagline: 'Immersive multi-part series with high cliffhanger frequency', description: 'WowTV delivers full-screen immersive multi-part series with a cliffhanger frequency benchmark that exceeds industry norms, creating compulsive re-engagement across its catalog.', icon_url: getAppIcon('ww', 'WowTV'), poster_url: getDramaPoster('ww'), platform_url: 'https://www.wowtv.com', rating: 4.5, download_count: '3M+', review_count: 167000, content_focus: 'Multi-Genre', specialties: ['Immersive', 'Multi-Part', 'Cliffhanger'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ptv2', name: 'Pocket TV', developer: 'Pocket Network', tagline: 'Localized English-cast revenge dramas with global base', description: 'Pocket TV expands from its strong global base into the U.S. with localized English-cast revenge drama productions blending international budgets with Western appeal.', icon_url: getAppIcon('ptv2', 'Pocket TV'), poster_url: getDramaPoster('ptv2'), platform_url: 'https://www.pockettv.com', rating: 4.5, download_count: '4M+', review_count: 213000, content_focus: 'Drama', specialties: ['Revenge', 'Localized', 'English Cast'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ku', name: 'Kuku TV', developer: 'Kuku Media', tagline: 'Vertical-first network transitioning serialized logic to the West', description: 'Kuku TV is an ambitious vertical-first network transitioning its highly successful fast-paced serialized content model into Western app store markets with increasing momentum.', icon_url: getAppIcon('ku', 'Kuku TV'), poster_url: getDramaPoster('ku'), platform_url: 'https://www.kukutv.com', app_store_url: 'https://apps.apple.com/us/app/kuku-tv-stream-drama-series/id6737497276', rating: 4.4, download_count: '5M+', review_count: 264000, content_focus: 'Multi-Genre', specialties: ['Serialized', 'Fast-Paced', 'Vertical'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ts', name: 'TopShort', developer: 'Jiuzhou', tagline: 'Historical fantasy and multicultural romance micro-dramas', description: 'TopShort specializes in culturally diverse micro-dramas blending historical fantasy, traditional settings, and modern romance storytelling for global audiences.', icon_url: getAppIcon('ts', 'TopShort'), poster_url: getDramaPoster('ts'), platform_url: 'https://www.topshort.tv', app_store_url: 'https://apps.apple.com/us/app/topshort-novels-and-drama/id6449445543', rating: 4.5, download_count: '4M+', review_count: 198000, content_focus: 'Drama', specialties: ['Historical', 'Fantasy', 'Cultural'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'mr', name: 'MoboReels', developer: 'Changdu', tagline: 'Urban romance, corporate rivalries, and modern soap operas', description: 'MoboReels delivers pocket-sized urban romance, corporate rivalry storylines, and modern soap-opera drama in compact episode formats designed for quick consumption.', icon_url: getAppIcon('mr', 'MoboReels'), poster_url: getDramaPoster('mr'), platform_url: 'https://www.moboreels.com', app_store_url: 'https://apps.apple.com/us/app/moboreels-short-drama-series/id6450243852', rating: 4.5, download_count: '3M+', review_count: 156000, content_focus: 'Romance', specialties: ['Urban', 'Corporate', 'Soap Opera'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'stv', name: 'ShortTV', developer: 'ShortTV Platform', tagline: 'Continuous vertical feed of rapid-fire family conflicts', description: 'ShortTV runs a continuous vertical scrolling feed of rapid-fire family conflict storylines, stepmother dramas, inheritance battles, and domestic suspense.', icon_url: getAppIcon('stv', 'ShortTV'), poster_url: getDramaPoster('stv'), platform_url: 'https://www.shorttv.com', app_store_url: 'https://apps.apple.com/us/app/id6446214316', rating: 4.4, download_count: '5M+', review_count: 231000, content_focus: 'Drama', specialties: ['Family', 'Conflict', 'Domestic'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ss', name: 'StarShort', developer: 'StarShort Studio', tagline: 'Action-romance mashups, underworld secrets, and redemption arcs', description: 'StarShort blends action-adventure with romance through underworld boss stories, redemption arcs, and bodyguard romance series targeting global thriller-romance fans.', icon_url: getAppIcon('ss', 'StarShort'), poster_url: getDramaPoster('ss'), platform_url: 'https://www.starshort.com', rating: 4.6, download_count: '2M+', review_count: 127000, content_focus: 'Romance', specialties: ['Action', 'Underworld', 'Redemption'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'vg', name: 'Vigloo', developer: 'Vigloo Streaming', tagline: 'Ultra-rapid 60-second episodic clips for zero-delay binging', description: 'Vigloo built its platform architecture for zero-delay binging with pre-loaded episodes that eliminate buffering and transitions designed to make stopping feel impossible.', icon_url: getAppIcon('vg', 'Vigloo'), poster_url: getDramaPoster('vg'), platform_url: 'https://play.google.com/store/apps/details?id=com.vigloo.app', app_store_url: 'https://apps.apple.com/us/app/vigloo-premier-short-dramas/id6503421271', rating: 4.4, download_count: '1.5M+', review_count: 79000, content_focus: 'Multi-Genre', specialties: ['Zero-Delay', 'Pre-Loaded', 'Binge'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'my', name: 'My Drama', developer: 'Apalon Apps', tagline: 'Fast-paced relationship dramas and high-society conflicts', description: 'My Drama delivers polished relationship drama and high-society conflict content with a clean UI and curated catalog appealing to audiences seeking sophisticated story arcs.', icon_url: getAppIcon('my', 'My Drama'), poster_url: getDramaPoster('my'), platform_url: 'https://www.mydrama.com', app_store_url: 'https://apps.apple.com/us/app/my-drama-stream-short-dramas/id6498713494', rating: 4.5, download_count: '2M+', review_count: 109000, content_focus: 'Drama', specialties: ['Relationship', 'High Society', 'Conflict'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'dw', name: 'DramaWave', developer: 'Wave Studio', tagline: 'Experimental formats and animated short drama hybrids', description: 'DramaWave experiments with animated hybrid sequences, light thriller crossovers, and non-linear storytelling techniques not attempted by mainstream micro-drama platforms.', icon_url: getAppIcon('dw', 'DramaWave'), poster_url: getDramaPoster('dw'), platform_url: 'https://www.dramawave.com', app_store_url: 'https://apps.apple.com/us/app/dramawave-dramas-reels/id6670430706', rating: 4.3, download_count: '400K+', review_count: 22000, content_focus: 'Multi-Genre', specialties: ['Experimental', 'Animated', 'Non-Linear'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ns', name: 'NetShort', developer: 'NetShort Group', tagline: 'Global hits blended with local casts for maximum discovery', description: 'NetShort operates an aggressive user discovery engine that blends proven global storyline formulas with locally cast productions to maximize audience size across markets.', icon_url: getAppIcon('ns', 'NetShort'), poster_url: getDramaPoster('ns'), platform_url: 'https://www.netshort.com', app_store_url: 'https://apps.apple.com/us/app/netshort-popular-dramas-tv/id6504849169', rating: 4.4, download_count: '3M+', review_count: 143000, content_focus: 'Multi-Genre', specialties: ['Local Cast', 'Global Formula', 'Discovery'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'cj', name: 'CandyJar', developer: 'CandyJar Media', tagline: 'Coin-unlocked melodramas and hidden-identity stories', description: 'CandyJar runs a coin-unlock economy around its melodrama and hidden-identity catalog, using daily reward systems and social sharing to drive organic user growth.', icon_url: getAppIcon('cj', 'CandyJar'), poster_url: getDramaPoster('cj'), platform_url: 'https://www.candyjar.tv', rating: 4.3, download_count: '1M+', review_count: 58000, content_focus: 'Drama', specialties: ['Melodrama', 'Hidden Identity', 'Coin Unlock'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'rt', name: 'RapidTV', developer: 'Rapid Streaming', tagline: 'High-emotion sequences tailored for continuous mobile viewing', description: 'RapidTV sequences its high-emotion content with precision timing, ensuring every episode concludes on an unresolved emotional beat that makes the next episode feel mandatory.', icon_url: getAppIcon('rt', 'RapidTV'), poster_url: getDramaPoster('rt'), platform_url: 'https://www.rapidtv.com', app_store_url: 'https://apps.apple.com/us/app/rapidtv/id6746744353', rating: 4.4, download_count: '2M+', review_count: 96000, content_focus: 'Drama', specialties: ['High Emotion', 'Continuous', 'Cliffhanger'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'btv', name: 'BonusTV', developer: 'Bonus Media', tagline: 'Freemium catalog with daily reward keys for romance loops', description: 'BonusTV runs a freemium catalog where daily reward keys unlock new romance episodes, creating an addictive daily check-in habit that sustains long-term audience retention.', icon_url: getAppIcon('btv', 'BonusTV'), poster_url: getDramaPoster('btv'), platform_url: 'https://www.bonustv.com', rating: 4.4, download_count: '2.5M+', review_count: 118000, content_focus: 'Romance', specialties: ['Freemium', 'Daily Reward', 'Romance Loop'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'mel', name: 'MeloShort', developer: 'MeloShort Labs', tagline: 'Localized urban romance and office politics micro-series', description: 'MeloShort produces localized urban romance and office politics content adapted for multiple regional markets, with English-language productions leading its Western expansion.', icon_url: getAppIcon('mel', 'MeloShort'), poster_url: getDramaPoster('mel'), platform_url: 'https://www.meloshort.com', rating: 4.4, download_count: '1.5M+', review_count: 73000, content_focus: 'Romance', specialties: ['Urban', 'Office Politics', 'Localized'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'sk', name: 'SnackShort', developer: 'SnackVideo Network', tagline: 'Micro-installments of trending internet fiction plotlines', description: 'SnackShort adapts the most-discussed internet fiction and viral storyline trends into mini-installment vertical dramas, surfacing trend-matched content through its discovery algorithm.', icon_url: getAppIcon('sk', 'SnackShort'), poster_url: getDramaPoster('sk'), platform_url: 'https://www.snackshort.com', app_store_url: 'https://apps.apple.com/us/app/snackshort/id6450035850', rating: 4.3, download_count: '2M+', review_count: 98000, content_focus: 'Multi-Genre', specialties: ['Trending', 'Internet Fiction', 'Algorithm'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'hs', name: 'HotShort', developer: 'HotShort Tech', tagline: 'Family betrayals and elite-society soap operas', description: 'HotShort targets high-intensity family betrayal drama and elite-society soap-opera content, building its catalog around the most emotionally charged storyline categories.', icon_url: getAppIcon('hs', 'HotShort'), poster_url: getDramaPoster('hs'), platform_url: 'https://www.hotshort.com', rating: 4.4, download_count: '2M+', review_count: 104000, content_focus: 'Drama', specialties: ['Family Betrayal', 'Elite Society', 'Soap Opera'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'pd2', name: 'PocketDramas', developer: 'Pocket Apps', tagline: 'Lighthearted romantic comedy shorts for easy viewing', description: 'PocketDramas keeps it fun with lighthearted romantic comedy vertical shorts, offering a stress-free option within the often emotionally intense mini-drama space.', icon_url: getAppIcon('pd2', 'PocketDramas'), poster_url: getDramaPoster('pd2'), platform_url: 'https://www.pocketdramas.com', rating: 4.4, download_count: '800K+', review_count: 42000, content_focus: 'Multi-Genre', specialties: ['Rom-Com', 'Lighthearted', 'Comedy'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ptv', name: 'Piccolo TV', developer: 'Piccolo Media', tagline: 'Artistic 3-minute continuous vertical series', description: 'Piccolo TV distinguishes itself with slightly longer 3-minute episodes allowing more narrative depth than standard micro-drama, attracting viewers seeking more substantive storytelling.', icon_url: getAppIcon('ptv', 'Piccolo TV'), poster_url: getDramaPoster('ptv'), platform_url: 'https://www.piccolo.tv', rating: 4.5, download_count: '600K+', review_count: 37000, content_focus: 'Drama', specialties: ['3-Minute', 'Artistic', 'Narrative Depth'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'tk', name: 'TickShort', developer: 'Tick Video', tagline: 'Short meme-adjacent comedic and dramatic vertical skits', description: 'TickShort occupies the intersection of meme culture and micro-drama, blending viral comedic hooks with dramatic storylines to capture both social video and narrative content audiences.', icon_url: getAppIcon('tk', 'TickShort'), poster_url: getDramaPoster('tk'), platform_url: 'https://www.tickshort.com', rating: 4.2, download_count: '1.5M+', review_count: 76000, content_focus: 'Multi-Genre', specialties: ['Meme', 'Comedy', 'Viral'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'su', name: 'Sua Novela', developer: 'Novela Network', tagline: 'Telenovela adaptations scaling fast in the U.S. English market', description: 'Sua Novela brings the telenovela tradition into vertical micro-drama with a rapidly expanding English-language catalog of passion, betrayal, and family-saga storylines.', icon_url: getAppIcon('su', 'Sua Novela'), poster_url: getDramaPoster('su'), platform_url: 'https://www.suanovela.com', rating: 4.4, download_count: '2M+', review_count: 109000, content_focus: 'Drama', specialties: ['Telenovela', 'Passion', 'Family Saga'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'ml', name: 'Melolo', developer: 'Melolo Video', tagline: 'Fast-scaling international contender with Western expansion', description: 'Melolo aggressively expanded into Western markets this year with a polished catalog of romance and revenge dramas, investing heavily in localized English content production.', icon_url: getAppIcon('ml', 'Melolo'), poster_url: getDramaPoster('ml'), platform_url: 'https://www.melolo.com', app_store_url: 'https://apps.apple.com/us/app/melolo-short-movie-tv/id6737513497', rating: 4.5, download_count: '3M+', review_count: 178000, content_focus: 'Romance', specialties: ['International', 'Localized', 'Romance'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
  { id: 'mn', name: 'Minis', developer: 'Muvi', tagline: 'AI-driven micro-drama framework for indie studio distribution', description: 'Minis by Muvi provides an AI-driven distribution framework enabling smaller and independent studios to publish mobile cliffhanger content at scale without major platform overhead.', icon_url: getAppIcon('mn', 'Minis'), poster_url: getDramaPoster('mn'), platform_url: 'https://www.minisshortvideos.com', rating: 4.2, download_count: '800K+', review_count: 38000, content_focus: 'Multi-Genre', specialties: ['AI-Driven', 'Indie Studio', 'Distribution'], region_origin: 'Global_Traction', quality_tier: 'Standard', featured: false, active: true },
];
